prefix : <https://id.kb.se/vocab/>

SELECT * WHERE {

  ?instance a :DigitalResource ;
      :category <https://id.kb.se/term/rda/OnlineResource> ;

  :hasTitle [ a :Title ;
      :mainTitle ?title ] ;
      :instanceOf _:work ;
      :publication [ :year|:date ?yearOrDate ;
      a :PrimaryPublication ;
      :agent [ a :Agent ;
        :label ?förlag ] ;
      :place [ a :Place ;
      :label ?plats ] ] .

  FILTER EXISTS {
        _:work a :Monograph .
        { _:work :category <https://id.kb.se/term/saogf/Ljudb%C3%B6cker> .}
        UNION
        { _:work :category <https://id.kb.se/term/barngf/Ljudb%C3%B6cker> .}
        }

  OPTIONAL { ?instance :identifiedBy [ a :ISBN ;
      :value ?ISBN ]
  }

  FILTER (regex(?yearOrDate,'202[4-5]'))
  FILTER (LANG(?title) = "")
}
