PREFIX : <https://id.kb.se/vocab/>
PREFIX marc: <https://id.kb.se/marc/>

SELECT DISTINCT ?instance ?cn
?isbn  {
?instance :identifiedBy [ a :ISBN ;
          :value ?isbn] .
VALUES (?isbn) {('9789189740099') ('9789189713185') ('9789127180536') ('9789137507644')
  }
  
?meta :mainEntity ?instance;
:controlNumber ?cn.
}
